### PR TITLE
Backport Support for i.MX8M Nano to Zeus

### PR DESCRIPTION
**Pull request by chrisdimich**

### CODE REVIEW

**Comment by mirzak** [comment]
I noticed that this PR broke Linux kernel boot on one my boards, more specifically [Coral Dev board](https://github.com/mirzak/meta-coral/tree/zeus/meta-coral-bsp) which an iMX8MQ and still using the 4.14 Linux kernel.

The Coral dev board is very similar to [imx8mqevk.conf](https://github.com/Freescale/meta-freescale/blob/master/conf/machine/imx8mqevk.conf), I have not tested on latter yet but I suspect that it would be similar problems there.

I will try to run a bisect to narrow down the commit, but wanted to report here to see if anyone has seen something similar or might have a logical explanation on why?

**Comment by otavio** [comment]
Broke how? Please open an issue with the details.

**Comment by mirzak** [comment]
Created issue, https://github.com/Freescale/meta-freescale/issues/331

**Comment by chrisdimich** [comment]
Hi,

We tested this on Nitrogen8M which is iMX8MQ based and we did not see this
issue.

Thanks,

Chris Dimich
Boundary Devices, LLC
www.boundarydevices.com
7 Orchard Road, Suite 102*｜*Lake Forest, CA 92630

**Pull request merged**
