### PR TITLE
Fixes needed for xwayland 23.x

### PR DESCRIPTION
**Pull request by kraj**
…BGRA8888

OE-core is soon upgrading to xwayland 23.x and this patch is already part of this release [1]

Be aware that this would be post mickledore release, so this patch is not backportable to mickledore, its only for upcoming master and beyond.

[1] https://gitlab.freedesktop.org/xorg/xserver/-/commit/24cd5f34f8edcc6621ed9c0f2b1a3df08de7488d

### CODE REVIEW

**Comment by kraj** [comment]
Dont merge it until oe-core gets the xwayland 23.x upgrade see [1] needs to land in master first.

[1] https://patchwork.yoctoproject.org/project/oe-core/patch/1681119256-25106-4-git-send-email-wangmy@fujitsu.com/

**Comment by kraj** [comment]
> Dont merge it until oe-core gets the xwayland 23.x upgrade see [1] needs to land in master first.
> 
> [1] https://patchwork.yoctoproject.org/project/oe-core/patch/1681119256-25106-4-git-send-email-wangmy@fujitsu.com/

this has been now merged in master see
https://git.openembedded.org/openembedded-core/commit/?id=35fdbd0ea81650a0421d50fb53989d96c5956331

so please merge this PR into master here as well.

**Comment by kraj** [comment]
Can we merge this please ? or else master is broken

**Review by MrCry0 — APPROVED** [review]

**Comment by thochstein** [comment]
Looks like xwayland 23.x is on OE-core mickledore. Can we backport this?

**Pull request merged**
