### PR TITLE
[scarthgap] Migrate to use Linux kernel v6.11.0 in linux-fslc

### PR DESCRIPTION
**Pull request by Livius90**
It was tested without any errors on the following boards:

- i.MX7D Pico-Pi - work :white_check_mark:
- i.MX93 11x11 EVK - work :white_check_mark:

To get and migrate the latest mainline kernel branch to [linux-fslc repo](https://github.com/Freescale/linux-fslc):
```bash
    git clone --single-branch --branch 6.11.x+fslc https://github.com/Livius90/linux-fslc.git
    cd linux-fslc
    git remote add fslc-mirror https://github.com/Freescale/linux-fslc.git
    git push -u fslc-mirror
```

Notes:
- you can use [linux-6.11.y](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.11.y) branch from [mainline Linux repo](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git) for migrating also.
- cryptodev-module: need to apply "[Fix build for Linux 6.7-rc1](https://github.com/cryptodev-linux/cryptodev-linux/commit/5e7121e45ff283d30097da381fd7e97c4bb61364)" patch otherwise cryptodev-linux 1.13 is not able to build in scarthgap. In further Yocto release branch it will not need in the future, because cryptodev-linux 1.14 got this [patch/fix finally](https://github.com/cryptodev-linux/cryptodev-linux/compare/cryptodev-linux-1.13...cryptodev-linux-1.14).

### CODE REVIEW

**Comment by Livius90** [comment]
In the next several days [Linux kernel v6.11 stable release](https://www.phoronix.com/news/Linux-6.11-rc7-Released#google_vignette) will be available. Please wait a little for the merging, i will try it also. It could be cool to get the latest v6.11 instead.

**Comment by otavio** [comment]
Sure, we can wait. Either way, first we need to send the update to the master branch and later we do the backport.

**Comment by Livius90** [comment]
@otavio 

[Linux kernel v6.11](https://www.kernel.org/) was tested without any errors on the following boards:

- i.MX7D Pico-Pi - work :white_check_mark:
- i.MX93 11x11 EVK - work :white_check_mark:

It is ready to use in linux-fslc.

**Comment by otavio** [comment]
I apologize to take longer to review this, and to be completely honest, I ended forgetting about this pull request.

I prepared the branch in the main repository with your respective branch. Is it possible for you to prepare the update to the master branch and then we apply it before merging this one?

Once you send the new pull request, I will merge it and then we do a rebase on this one on top of the current branch and then we can merge it directly.

**Comment by Livius90** [comment]
Yes i can make a new pull request for `master`. But cryptodev-module need a patch fix just for scarthgap to able to use v6.11.x in scarthgap also. It can be a separated cryptodev PR also later only for scarthgap.

**Pull request closed without merging**
