### PR TITLE
Zeus: Backport EULA handling enhancements

### PR DESCRIPTION
**Pull request by thochstein**

### CODE REVIEW

**Comment by otavio** [comment]
Why kind of test has been done here?

**Comment by thochstein** [comment]
You're right, let me do a build here too. Sorry.

**Comment by thochstein** [comment]
I'm actually doing a more focused test, making sure I can unpack every recipe that has `fsl-eula-unpack.bbclass`.

I've never setup for qoriq, though, so those I've just manually checked the `LIC_FILES_CHKSUM`.

This recipe is unfortunately not covered by my list of licenses:
meta-freescale/recipes-extended/hyperrelay/hyperrelay_git.bb

Is this recipe broken anyway because it refers to git.freescale.com?

**Comment by zandrey** [comment]
@thochstein can you please add a V10 license to the class?

I'm integrating updated components now to the layer, and following entry in the class is missing:

```
FSL_EULA_FILE_MD5SUM_LA_OPT_NXP_SOFTWARE_LICENSE_V10 = "fd4b227530cd88a82af6a5982cfb724d"
```

Can you verify the MD5 and add it to `fsl-eula-unpack.bbclass`?

Thanks a lot!

-- andrey

**Comment by otavio** [comment]
@zandrey ideally it comes as a patch in your PR, so it is clear where it is coming from.

Also, the patch should aim the master branch and this is for zeus (a backport) ;-)

**Comment by thochstein** [comment]
@zandrey , that is the correct v10 checksum.

**Comment by zandrey** [comment]
@otavio Got it, thanks a lot! I was just thinking that the license update should come from NXP, but I can also push it in. And yes - the new kernel is meant for `master`, sorry. I didn't pay much attention to this PR header. 😄 

@thochstein Thanks for confirmation, I would introduce it with my next PR.

-- andrey

**Pull request merged**
