### PR TITLE
Fix SOC override priority change and adjust imx-alsa-plugins version handling

### PR DESCRIPTION
**Pull request by thochstein**

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
Considering what we discussed, the SoC overrides (e.g., `mx8-generic-bsp:mx8-nxp-bsp`) ought also to go to after the feature overrides, so it provides a higher restriction.

**Comment by thochstein** [comment]
> Considering what we discussed, the SoC overrides (e.g., `mx8-generic-bsp:mx8-nxp-bsp`) ought also to go to after the feature overrides, so it provides a higher restriction.

This is not how it used to work, so not what I thought we discussed. The commit is about making the priorities align with what was before. This is what the list looked like before:

```
MACHINEOVERRIDES="aarch64:armv8a:imx:use-nxp-bsp:mx8:mx8x:imxdrm:imxdpu:imxgpu:imxgpu2d:imxgpu3d:mx8qxp:imx8qxp-mek"
```

The way I would describe it is SOC groups/families first, then features, then SOC.

**Comment by thochstein** [comment]
Okay, I think it can work. The chances of it breaking a recipe seem pretty small.

To make sure we're on the same page, I'd like to map the generic terms to a specific example. This is what we have if we keep the priorities of the old design:

```
|                        | MACHINEOVERRIDES="\                                         |
|                        | aarch64:armv8a:use-nxp-bsp:\                                |
| generic i.MX overrides | imx-generic-bsp:imx-nxp-bsp:\                               |
| SoC group overrides    | mx8-generic-bsp:mx8-nxp-bsp:mx8x-generic-bsp:mx8x-nxp-bsp:\ |
| feature overrides      | imxdrm:imxdpu:imxgpu:imxgpu2d:imxgpu3d:\                    |
| SoC specific overrides | mx8qxp-generic-bsp:mx8qxp-nxp-bsp:\                         |
|                        | imx8qxp-mek"                                                |
```

And this is what we have after swapping the feature and SoC group priorities:

```
|                        | MACHINEOVERRIDES="\                                         |
|                        | aarch64:armv8a:use-nxp-bsp:\                                |
| generic i.MX overrides | imx-generic-bsp:imx-nxp-bsp:\                               |
| feature overrides      | imxdrm:imxdpu:imxgpu:imxgpu2d:imxgpu3d:\                    |
| SoC group overrides    | mx8-generic-bsp:mx8-nxp-bsp:mx8x-generic-bsp:mx8x-nxp-bsp:\ |
| SoC specific overrides | mx8qxp-generic-bsp:mx8qxp-nxp-bsp:\                         |
|                        | imx8qxp-mek"                                                |
```

**Comment by otavio** [comment]
Yes, your understanding is correct. Thanks for reconsidering it.

**Review by otavio — APPROVED** [review]

**Pull request merged**
