### PR TITLE
qoriq atf updates

### PR DESCRIPTION
**Pull request by ting-liu**
LSDK 20.12 supports two atf versions: 1.5 and 2.3. Rename atf_git.bb to
atf_1.5.bb which supports all layerscape arm64 machines. Add atf_2.3.bb
which supports lx2160a and lx2162a. Also upgrade atf-tools to 2.3.

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
Please rename the `atf` recipes for `qoriq-atf` so it is clear what uses it.

**Comment by ting-liu** [comment]
> Please rename the `atf` recipes for `qoriq-atf` so it is clear what uses it.

I have renamed atf to qoriq-atf. The pull request was updated to base on the latest master branch. Please review.

**Review by otavio — APPROVED** [review]

**Comment by zandrey** [comment]
@ting-liu 

Can you also review and rename appends in _meta-freescale-3rdparty_ repository?

Current `master` build is broken, as appends in _meta-freescale-3rdparty_ are still targeting old recipe names:
```
ERROR: No recipes in default available for:
      /development/yocto-master/meta-freescale-3rdparty/recipes-bsp/atf/atf_git.bbappend
      /development/yocto-master/meta-freescale-3rdparty/recipes-bsp/u-boot/u-boot-qoriq_2019.10.bbappend
```

-- andrey

**Comment by ting-liu** [comment]
> @ting-liu
> 
> Can you also review and rename appends in _meta-freescale-3rdparty_ repository?
> 
> Current `master` build is broken, as appends in _meta-freescale-3rdparty_ are still targeting old recipe names:
> 
> ```
> ERROR: No recipes in default available for:
>       /development/yocto-master/meta-freescale-3rdparty/recipes-bsp/atf/atf_git.bbappend
>       /development/yocto-master/meta-freescale-3rdparty/recipes-bsp/u-boot/u-boot-qoriq_2019.10.bbappend
> ```
> 
> -- andrey

PRs are sent out.

**Pull request merged**
