### PR TITLE
jailhouse: update to lf-5.15.52_2.1.0

### PR DESCRIPTION
**Pull request by ricardosalveti**
Update jailhouse to the NXP lf-5.15.52_2.1.0 release, and clean up the packaging logic to align with the latest release.

Packaging changes:
- Drop build instructions for tools as that is now built as part of the
  main Makefile
- Drop JH_CONFIG and related tools variables as they are not required
- Change do_compile and do_install to prepend to allow the logic from
  setuptools3 to be executed (and package pyjailhouse properly)
- Drop kernel from PACKAGE_BEFORE_PN, as it wasn't really used in the
  end, and doesn't work correctly with usrmerge. Prefer removing libdir
  that gets appended by setuptools3 for module split to work correctly
  with and without usrmerge.
- Update FILES for pyjailhouse to include all the python related files
   produced by the build

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
It seems the cache metadata is not happy with kernel version there and PACKAGE_BEFORE_PN, testing it a bit more (moving to draft)

**Comment by ricardosalveti** [comment]
All good now after removing the usage of kernel version and removing kernel from PACKAGE_BEFORE_PN.

**Comment by ricardosalveti** [comment]
@quaresmajose @angolini ^^

**Comment by quaresmajose** [comment]
Thanks for fixing the remaining issues.

**Pull request merged**
