### PR TITLE
Revert "fsl-dynamic-packagearch: fix MACHINE_SOCARCH definition"

### PR DESCRIPTION
**Pull request by thochstein**
This change makes no sense. MACHINE_SOCARCH must include the suffix that makes the value SOC-specific. Otherwise, errors such as this occur:
```
ERROR: imx-dpu-g2d-2.1.12-r0 do_create_spdx_setscene: Recipe imx-dpu-g2d is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  tmp/deploy/spdx/armv8a/packages/libg2d-dev.spdx.json
    (matched in manifest-armv8a-imx-pxp-g2d.create_spdx)
  tmp/deploy/spdx/armv8a/packages/libg2d2.spdx.json
    (matched in manifest-armv8a-imx-pxp-g2d.create_spdx)
```

This reverts commit 6579ce9b77f0036454478b2e07694f7314f97867.

### CODE REVIEW

**Comment by jmarcoscosta** [comment]
Hello, @thochstein (cc @otavio)

I wasn't able to reproduce this error you mentioned. Could you please give me some details on that?
Besides, both `imx-dpu-g2d` and `imx-pxp-g2d` are providers of `virtual/libg2d`, so logically only one of them should be used, hence this conflict where both try to install those jsons seems odd to me.

**Comment by thochstein** [comment]
Hi @jmarcoscosta, you can reproduce the issue by building two implementations of `virtual/libg2d` in the same build folder, i.e., by building different SOCs that use different g2d implementations. Each implementation is SOC-specific and so needs an SOC arch for the package feed to work properly.

**Comment by jmarcoscosta** [comment]
I'm building `imx-pxp-g2d-2.1.0+gitAUTOINC+8d8b48c7c3-r0` for imx93 and I get this error at `do_compile`:
```
| g2d.c: In function 'g2d_cache_op':
| g2d.c:520:14: error: 'struct pxp_mem_flush' has no member named 'dmabuf_fd'
|   520 |     mem_flush.dmabuf_fd = dma_buf_ptr->dmafd;
|       |              ^
| make[1]: Leaving directory '/home/jmcosta/kas/microej/build/tmp-glibc/work/cortexa55-oe-linux/imx-pxp-g2d/2.1.0+gitAUTOINC+8d8b48c7c3-r0/git/g2d'
| make[1]: *** [Makefile:34: g2d.o] Error 1
```
Have you seen this before?

**Comment by thochstein** [comment]
It builds for me. I am using `fsl-xwayland` distro, perhaps that is the difference?

**Pull request merged**
