### PR TITLE
Graphics driver updates for 5.4.47-2.2.0 release

### PR DESCRIPTION
**Pull request by thochstein**

### CODE REVIEW

**Comment by otavio** [comment]
@thochstein, how has this been tested? In the last upgrade, I ended [reverting](https://github.com/Freescale/meta-freescale/commit/98eb5673ba2ae2b6cb91dd760511e3bcaae11c1d) the packaging rework due to runtime errors.

**Comment by zandrey** [comment]
@thochstein 

Unfortunately this PR (when extracted as a patch series and applied on top of _master_) fails to build for both _imx8mmevk_ and _imx8mpevk_ machines with following errors:

```
--- imx8mmevk:
ERROR: imx-gpu-sdk-5.5.3-r0 do_package_qa: QA Issue: /opt/imx-gpu-sdk/OpenVG/VGStressTest/OpenVG.VGStressTest_Wayland contained in package imx-gpu-sdk requires libOpenVG.so()(64bit), but no providers found in RDEPENDS_imx-gpu-sdk? [file-rdeps]
ERROR: imx-gpu-sdk-5.5.3-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /development/yocto-master/build-output/work/cortexa53-crypto-mx8mm-fsl-linux/imx-gpu-sdk/5.5.3-r0/temp/log.do_package_qa.30027
ERROR: Task (/development/yocto-master/yocto-build-appliance/meta-freescale-distro/recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.5.3.bb:do_package_qa) failed with exit code '1'

--- imx8mpevk:
ERROR: imx-gpu-sdk-5.5.3-r0 do_package_qa: QA Issue: /opt/imx-gpu-sdk/OpenVG/VGStressTest/OpenVG.VGStressTest_Wayland contained in package imx-gpu-sdk requires libOpenVG.so()(64bit), but no providers found in RDEPENDS_imx-gpu-sdk? [file-rdeps]
ERROR: imx-gpu-sdk-5.5.3-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /development/yocto-master/build-output/work/cortexa53-crypto-mx8mp-fsl-linux/imx-gpu-sdk/5.5.3-r0/temp/log.do_package_qa.4122
ERROR: Task (/development/yocto-master/yocto-build-appliance/meta-freescale-distro/recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_5.5.3.bb:do_package_qa) failed with exit code '1'

```

**Comment by thochstein** [comment]
Thanks, @zandrey, seems I will need to upgrade `imx-gpu-sdk` at the same time.

**Comment by zandrey** [comment]
> Thanks, @zandrey, seems I will need to upgrade `imx-gpu-sdk` at the same time.

@thochstein Do you know which version of `imx-gpu-sdk` is planned to be committed?

The reason for this question is: there is an issue with building Vulkan demos in the GPU SDK due to deprecation of `VK_FORMAT_BEGIN_RANGE`.

I've addressed it for gstreamer in #545, and it is also resolved in GPU SDK starting from version _5.6.1_, commit [42a8ae8042bfdb96c70ff399c2852c3a0650fe1b](https://github.com/NXPmicro/gtec-demo-framework/commit/42a8ae8042bfdb96c70ff399c2852c3a0650fe1b).

I guess it makes sense to integrate at least that version of SDK, otherwise Vulkan samples would fail to build and should be disabled.

-- andrey

**Comment by thochstein** [comment]
> I've addressed it for gstreamer in #545, and it is also resolved in GPU SDK starting from version _5.6.1_, commit [42a8ae8042bfdb96c70ff399c2852c3a0650fe1b](https://github.com/NXPmicro/gtec-demo-framework/commit/42a8ae8042bfdb96c70ff399c2852c3a0650fe1b).

That is the version I am working on. I can make a new PR to share, but I'm having a build break with `mesa`.

**Comment by thochstein** [comment]
The `mesa` break appears to be recent, fixed upstream: https://cgit.freedesktop.org/mesa/mesa/commit/?id=cf17d6251653f4a98e7c4f904ea2f0bc0ecedd5c. Cleaning my drive to make some room to test it.

**Review by otavio — APPROVED** [review]

**Comment by thochstein** [comment]
The `mesa` patch is in now in OE-core, dropped the local one.

**Pull request merged**
