### PR TITLE
imx-base.inc: use 0x80008000 as the UBOOT_ENTRYPOINT for mx6ul, mx6ul…

### PR DESCRIPTION
**Pull request by mferland**
…l and mx6ulz

Based on the different reference manuals, the DDR controller for the
mx6ul, mx6ull and mx6ulz is at 0x80000000 and not 0x10000000 like the
imx6 dual or quad for example.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>

### CODE REVIEW

**Review by otavio — COMMENTED** [review]
@thochstein, can you take a look?

**Comment by thochstein** [comment]
It's been this way for years. Are you seeing an error? I'll have to ask internally to see if there is a reason for the discrepancy.

**Comment by mferland** [comment]
I recently upgraded from thud to hardknott and also switched to fitImage when I stumbled on this issue. Kernel wouldn't start anymore (u-boot was loading without issues), changing UBOOT_ENTRYPOINT to a sane value fixed it for me.

**Comment by otavio** [comment]
@mferland please prepare a backport PR (using `git cherry-pick -x`).

**Pull request merged**
