### PR TITLE
simplify the use of imx-boot-containers

### PR DESCRIPTION
**Pull request by MaxKrummenacher**

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
@zandrey @thochstein could you guys review? It looks like a great simplification.

**Comment by zandrey** [comment]
This looks good, I'll run it through the CI now and give a feedback on testing round.

-- andrey

**Comment by thochstein** [comment]
Looks good to me 👍

**Review by zandrey — APPROVED** [review]
`Tested-by: Andrey Zhizhikin <andrey.z@gmail.com> #imx8mm-lpddr4-evk imx8mn-ddr4-evk imx8mp-lpddr4-evk imx8mq-evk`

**Pull request merged**
