### PR TITLE
wic: Fix image generation for i.MX

### PR DESCRIPTION
**Pull request by texierp**
Some boards expects a specific binary name.

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Signed-off-by: Joris Offouga <offougajoris@gmail.com>

### CODE REVIEW

**Comment by otavio** [comment]
I understand the change but isn't it always: `u-boot.imx` and `SPL` + `u-boot.img`?

**Comment by texierp** [comment]
In fact, with the WaRP7, we have to flash the following file : u-boot-dtb.imx [1]
So, without this change, wic image creation fail.

[1] http://git.denx.de/?p=u-boot.git;a=blob;f=board/warp7/README;h=579bb2de38a9d40fd5972193d4722b765b0b512c;hb=HEAD#l35

**Comment by otavio** [comment]
So your commit log is misleading.

However, last time I checked, the u-boot-dtb.imx and u-boot.imx were the same (same checksum) and we could simply keep using the same name.

**Comment by texierp** [comment]
Indeed, I just update the commit log, and I removed the part related to SPL & u-boot.img.

Now, I kept only the wic script with bootpart, good for you ?

**Pull request merged**
