### PR TITLE
RFC: mesa: provide a downgraded recipe

### PR DESCRIPTION
**Pull request by MaxKrummenacher**
@thochstein
Is an upgrade to the i.MX forks of libdrm/wayland-protocols shortly planned so that we don't need such a hack?

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
@thochstein can you do the upgrade so we don't need this downgrade?

**Comment by thochstein** [comment]
Working on it. I found we need `wayland-protocols` upgrade as well.

**Comment by thochstein** [comment]
See #1015

**Comment by otavio** [comment]
I merged it as this fixed a build failure. I am closing this now.

**Pull request closed without merging**
