### PR TITLE
gstreamer1.0: update to NXP's MM_04.05.06_2008_L5.4.47 branches

### PR DESCRIPTION
**Pull request by zdobersek**
Update the GStreamer packages to the MM_04.05.06_2008_L5.4.47 branches
that are based on the 1.16.2 release.

Updating gstreamer1.0-plugins-base allows deleting one local patch
that is already included in the upstream 1.16.2 release.

imx-vpuwrap and imx-gst1.0-plugins packages are also updated to these
branches and also have their versions increased to 4.5.6.

Signed-off-by: Zan Dobersek <zdobersek@igalia.com>

### CODE REVIEW

**Comment by otavio** [comment]
Awesome; would you mind to split the commit on individual commits, one per recipe?

**Comment by zdobersek** [comment]
Yeah, I can.

**Comment by zdobersek** [comment]
@otavio split it into separate commits.

If possible, also merge this into gatesgarth to align the branches there as well.

**Comment by otavio** [comment]
@zdobersek the gatesgarth uses the 2.1.x NSP release so to upgrade it we need to finish the upgrade on master first.

**Comment by zdobersek** [comment]
@otavio did you mean 2.2.x on gatesgarth? On master, there's optee still using the 2.1.0 version. Is there anything beyond that that needs updating?

**Comment by otavio** [comment]
We have the 5.4.47-2.2.x only on master for now. We are still finish the upgrade and testing before we can consider any backport.

**Pull request merged**
