### PR TITLE
Backport NXP BSP 5.10.35_2.0.0 to Hardknott

### PR DESCRIPTION
**Pull request by angolini**
Backport to Hardknott the latest NXP BSP (5.10.35_2.0.0) which was released based on Hardknott.

The main reason is that the NXP BSP was released based on the current stable branch. In case we backport it to the hardknott from community, we are up to date with the NXP fork. Otherwise, the NXP release fork will be the latest.

So far, this PR does not include the gstreamer patches being reviewed here: https://github.com/Freescale/meta-freescale/pull/856

I understand the next stable is planned for almost 1 month from now. But I think this is the first time we have a NXP BSP release synchronized with the current stable branch (as far as I remember), so I think it's might be beneficial for others to have the NXP BSP backported, as well.

Please let me know what you think.

### CODE REVIEW

**Comment by angolini** [comment]
@thochstein FYI

**Comment by otavio** [comment]
Thanks @angolini for opening this PR for further discussion. Folks, I  asked her to open it so we could have people to comment here and share their views.

In general, I don't consider doing this kind of backports however @angolini has a valid point when she mentions we'd be aligned with NXP on stable. Also, it'd help to compare results with their BSP release when need.

So please share your point of view so we can consider merging it or not.

**Comment by angolini** [comment]
Just included the patches from #856

**Comment by angolini** [comment]
Waiting the review of #862

**Comment by angolini** [comment]
In the force push I remove this patch (I had created for my local build):

```
6c27225c imx8mm-evk: Remove dependecy on qca9377
```

And include the patches already merged on master:

```
b821d72e qcacld: Drop BSP support
758ef644 imx8mm-evk.inc: Drop qca9377
```

**Comment by angolini** [comment]
I'm not sure we want to bring this patch: https://github.com/Freescale/meta-freescale/commit/9ddb7f820ba5dab5eb0a5f674d73114dcfee58f7

**Comment by otavio** [comment]
> I'm not sure we want to bring this patch: [9ddb7f8](https://github.com/Freescale/meta-freescale/commit/9ddb7f820ba5dab5eb0a5f674d73114dcfee58f7)

I think we should. Do you have any concern?

**Pull request merged**
