### PR TITLE
Upgrade layer to NXP rel_imx_5.4.3_2.0.0 tag

### PR DESCRIPTION
**Pull request by zandrey**
Following components were upgraded:

*U-Boot:*
Commit: `47c19229783cd51821d1cc13bedb0dd5850f00da`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `imx_v2019.04_5.4.3_2.0.0`

*Kernel:*
Commit: `fd263a3edd95dfe812397fabf1059b5f99bba2ab`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `imx_5.4.3_2.0.0`

*qcacld-2.0-imx:*
Commit: `7dc91e5977f31d60741c55682564788c0f930163`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `IMX_CNSS.LEA.NRT_3.0_KRL5.4`

*imx-gst1.0-plugin:*
Commit: `77760c4e4177f2afd80d7d09f3d1fb137b96adfa`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `MM_04.05.04_2002_L5.4.3`

*gst-plugins-base:*
Commit: `5221bd72a116341738ab060b195b38a2cbed1c58`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `MM_04.05.04_2002_L5.4.3`

*gst-plugins-good:*
Commit: `3bcc85705695ee629ac3fb687411bb196d231918`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `MM_04.05.04_2002_L5.4.3`

*gst-plugins-bad:*
Commit: `eea4cfe9315a9c648d116cfff3cd532e9a31237d`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `MM_04.05.04_2002_L5.4.3`

*gstreamer:*
Commit: `a4c220605ac0923596b89f4f07c05d235bc09259`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `MM_04.05.04_2002_L5.4.3`

*wayland-protocols-imx:*
Commit: `ee18c1f66877f7fb652467c349108395c20d4f9a`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `wayland-protocols-imx-1.18`

*weston-imx:*
Commit: `f6a7d35650121fbe7c20d4cbe0eaac730fab3b2a`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `weston-imx-8.0`

*libdrm-imx:*
Commit: `f421c9c8c4b8fe48d9e6ef43910e98569c94a4b2`
Tag:    `rel_imx_5.4.3_2.0.0`
Branch: `libdrm-imx-2.4.99`

Build has been verified on *i.MX8M Mini EVK*. Command-line and Multimedia images are booting OK.

*i.MX8M Nano EVK* machine has only been built - no runtime testing is performed, as I'm currently lacking the board.

This PR is rebased on top of PR #333 and should be integrated together with it.

Currently, there id one outstanding issue with this upgrade:
- GStreamer Video Playback is non-functional, no output is present on the screen

-- andrey

### CODE REVIEW

**Comment by thochstein** [comment]
@zandrey, sorry, but these are mostly supposed to be targeting 5.4.3-1.0.0. The 2.0.0 release is not a fully tested release, and the community has already reported an issue with gstreamer on 6DL. Perhaps only weston is okay to move to latest.

**Comment by zandrey** [comment]
> 
> @zandrey, sorry, but these are mostly supposed to be targeting 5.4.3-1.0.0. The 2.0.0 release is not a fully tested release, and the community has already reported an issue with gstreamer on 6DL. 

Ups, I thought we would advance to 2.0.0 since the head of linux-imx is tagged with `rel_imx_5.4.3_2.0.0`. I couldn't find any 1.0.0 references, but was able to locate `rel_imx_5.4.3_2.0.0` in all repos on *codeaurora*.

If there is tag for 1.0.0 release - can you please share it so I can rebase all this work onto it?

> Perhaps only weston is okay to move to latest.

Noted, this I would keep.

**Comment by zandrey** [comment]
> 
> 
> You can drop the `fsl-eula-unpack.bbclass` change. I needed it in my graphics PR. Seems you might not have rebased on my PR?

I did, and this got merged in! 😉 Would drop it, thanks for noting.

**Comment by thochstein** [comment]
> If there is tag for 1.0.0 release - can you please share it so I can rebase all this work onto it?

I see. Our 1.0.0 release was a bit of a different process where we aligned our i.MX and qoriq kernels. The layer containing the recipes for this release are here:

https://source.codeaurora.org/external/imx/meta-imx/?h=zeus-5.4.3-1.0.0

**Comment by zandrey** [comment]
> 
> 
> > If there is tag for 1.0.0 release - can you please share it so I can rebase all this work onto it?
> 
> I see. Our 1.0.0 release was a bit of a different process where we aligned our i.MX and qoriq kernels. The layer containing the recipes for this release are here:
> 
> https://source.codeaurora.org/external/imx/meta-imx/?h=zeus-5.4.3-1.0.0

Got it. I guess after this info most of this work could be stashed away... I would start working on the upgrade to `1.0.0` release then.

BTW, any chance *GStreamer* issue could be addressed in a reasonable timeframe? In this case we could jump straight to `2.0.0` release with this PR. Anything I can help with?

@otavio After the info from @thochstein, I think it does not make much sense for this PR to be integrated, at least until the *GStreamer* is solved. I would keep the branch in my fork for future use, cherry pick 2 commits for *Weston* and *Wayland-Protocols*, and would restart the upgrade with `1.0.0` meta information.

-- andrey

**Comment by otavio** [comment]
Agreed, please cherry-pick the required commits and prepare it based on `1.0.0`.

**Pull request closed without merging**
