### PR TITLE
imx-sc-firmware: Upgrade to 1.6.0 version

### PR DESCRIPTION
**Pull request by panfir**
Signed-off-by: Cristinel Panfir <cristinel.panfir@nxp.com>

### CODE REVIEW

**Comment by otavio** [comment]
Please, don't simplify the compatibility list.

**Comment by fbertux** [comment]
Why the license checksum was changed?

Follow the OE-Core [guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Describing_license_changes)

**Comment by panfir** [comment]
> Why the license checksum was changed?
> 
> Follow the OE-Core [guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Describing_license_changes)

The `EULA` v15 is on a PR#[352](https://github.com/Freescale/meta-freescale/pull/532) along with some other graphics patches.

**Comment by fbertux** [comment]
Ok. You need to add this to the commit log.

Thanks!

**Comment by panfir** [comment]
done

**Review by otavio — APPROVED** [review]

**Pull request merged**
