### PR TITLE
multiple uboot for single machine

### PR DESCRIPTION
**Pull request by bmx666**
A long time ago I implemented a workaround to support multiple u-boot builds for the same machine.
This saved our project several hours every day on builds (16 different U-boots) because the image was common to all machines, only U-boot had a few changes per machine configuration. All wic-images are generated at once, separate tasks are not needed.

It still supports the original way of configuration, but for multiple u-boot I added flags for the same env vars.

For example, original machine configs for boards M1 and M2 :

```
# MACHINE M1
KERNEL_DEVICETREE = "freescale/imx8mp_m1.dtb"
IMXBOOT_TARGETS = "flash_evk"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "imx8mp_m1_defconfig,sdcard"
UBOOT_DTB_NAME = "imx8mp_m1.dtb"
```

```
# MACHINE M2
KERNEL_DEVICETREE = "freescale/imx8mp_m2.dtb"
IMXBOOT_TARGETS = "flash_evk"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "imx8mp_m2_defconfig,sdcard"
UBOOT_DTB_NAME = "imx8mp_m2.dtb"
```

New unified machine config for both boards M1 and M2

```
# MACHINE M1 and M2
KERNEL_DEVICETREE = "\
    freescale/imx8mp_m1.dtb \
    freescale/imx8mp_m2.dtb \
"
IMXBOOT_TARGETS = "flash_evk"
UBOOT_CONFIG = "m1 m2"

UBOOT_CONFIG[m1] = "imx8mp_m1_defconfig,sdcard"
UBOOT_CONFIG[m2] = "imx8mp_m2_defconfig,sdcard"

UBOOT_DTB_NAME[m1] = "imx8mp_m1.dtb"
UBOOT_DTB_NAME[m2] = "imx8mp_m2.dtb"

WKS_FILE = "${IMAGE_BASENAME}.wks.in"
```

And instead of using common wks.in like
```
part u-boot --source rawcopy --sourceparams="file=imx-boot" ...
```

I need to create 2 extra wks.in differing only by imx-boot

**my-image-m1.wks.in**
```
part u-boot --source rawcopy --sourceparams="file=imx-boot-imx8mp-m1.bin-flash_evk" ...
```

**my-image-m2.wks.in**
```
part u-boot --source rawcopy --sourceparams="file=imx-boot-imx8mp-m2.bin-flash_evk" ...
```

It would also be nice to have **IMXBOOT_TARGETS** separated by configurations, but this was not necessary in my project, so I left it just "flash_evk"

I will left it here as draft PR, maybe someone will refactor it and implement better design.

### CODE REVIEW

**Comment by otavio** [comment]
The idea is good so please split this in two commits.

**Comment by bmx666** [comment]
There is also one trick I forgot to mention how to generate multiple wic-images at once. For example your build is using **my-image.bb** and machine's configuration includes U-boot configs **m1** and **m2**, and `WKS_FILE = "${IMAGE_BASENAME}.wks.in"`

You should create wks.in in wic folder for each u-boot configs with required image prefix (ex, "my-image"):

- meta-mylayer/wic/my-image-common.wks.in
- meta-mylayer/wic/my-image-m1.wks.in
- meta-mylayer/wic/my-image-m2.wks.in

Suppose you have a main image recipe located at
- recipes-images/images/my-image.bb

To cheat "do_image_wic" you should rename `my-image.bb` into `my-image-common.bb`

Then you should create common and dummy image recipes with the same suffixes for every U-boot configs:
- recipes-images/images/my-image-common.bb
- recipes-images/images/my-image-m1.bb
- recipes-images/images/my-image-m2.bb

content of dummy image recipes:
```
require my-image-common.bb
```

and then you should create a new fake recipe `my-image.bb` with content
 ```
SUMMARY = "Recipe to build multiple BLABLA images"

LICENSE = "MIT"

inherit image

do_rootfs[noexec] = "1"
do_rootfs_wicenv[noexec] = "1"
do_image[noexec] = "1"
do_image_wic[noexec] = "1"
do_image_complete[noexec] = "1"

do_clean[depends] = "\
	my-image-common:do_clean \
	my-image-m1:do_clean \
	my-image-m2:do_clean \
"

do_cleanall[depends] = "\
	my-image-common:do_cleanall \
	my-image-m1:do_cleanall \
	my-image-m2:do_cleanall \
"

do_cleansstate[depends] = "\
	my-image-common:do_cleanall \
	my-image-m1:do_cleansstate \
	my-image-m2:do_cleansstate \
"

IMAGE_NAMES = "my-image-common"
DEPENDS = "my-image-common"

IMAGE_NAMES_remove_unified8mp = "my-image-common"
IMAGE_NAMES_append_unified8mp = "\
	my-image-m1 \
	my-image-m2 \
"

DEPENDS_remove_unified8mp = "my-image-common"
DEPENDS_append_unified8mp = "\
	my-image-m1 \
	my-image-m2 \
"

# Set target image variables
TARGET_IMAGES = "${IMAGE_NAMES}"
TARGET_MACHINES = "${MACHINE_${IMAGE_NAMES}}"
```

> NOTE: replace unified8mp on your unified machine

In that case, **my-image** will create `my-image-common` for the original machine config (each machine has its own U-boot config) or multiple my-image-XXX for each U-boot configs which are defined in unified machine's config.

**Review by angolini — COMMENTED** [review]
I would prefer to have all the descriptions gathered in the PR description instead of in the comment sections. Would you mind including the text from [1] to the PR description?



[1] https://github.com/Freescale/meta-freescale/pull/1439#issuecomment-1447240774

**Comment by MrCry0** [comment]
This good idea comes right in time to be used with the coming mfgtool class to have spl/u-boot/kernel built with different configs for a main image and a mfgtool bundle.

**Pull request closed without merging**
