### PR TITLE
Recipes bsp

### PR DESCRIPTION
**Pull request by thochstein**

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
@MaxKrummenacher @gibsson @zandrey please review.

**Comment by gibsson** [comment]
Looks good to me. I wish there was some changelog for the binary packages but since it's not there on meta-imx either I figure it doesn't exist.

**Comment by thochstein** [comment]
I can work on it, it takes some time to calculate...

**Comment by otavio** [comment]
@thochstein let us know when it is done ...

**Pull request merged**
