### PR TITLE
Chromium i.MX patches

### PR DESCRIPTION
**Pull request by thochstein**
Moves the work for https://github.com/Freescale/meta-freescale/pull/1053 to a branch of my fork.

### CODE REVIEW

**Comment by jwzl** [comment]
Dear @thochstein :
  I downgrade to 96.0.4664.110, and it seems that it's same as 98.0.4758.102. So I consider that no need to downgrade to 96.0.4664.110 for me.

And the playing video is still 100% CPU. and after 4Hour,  chromium will have 1.5GB RAM usage. some times,

**Comment by jwzl** [comment]
Okay，thank you very much!

**Comment by jwzl** [comment]
Why blocked this pull request ?

**Comment by otavio** [comment]
It needs upgrading and fixing. Also, someone needs to step up to maintain these patches.

**Comment by otavio** [comment]
Closed in favor of #1375.

**Pull request closed without merging**
