### PR TITLE
[zeus] linux-fslc(-lts): add CONFIG_NET_SCH_FQ_CODE=y and necessary depends

### PR DESCRIPTION
**Pull request by schnitzeltony**
Otherwise modern systemd complains:

| Feb 05 13:22:36 some-host systemd-sysctl[186]: Couldn't write 'fq_codel' to 'net/core/default_qdisc', ignoring: No such file or directory
| Feb 05 13:22:36 some-host systemd-sysctl[186]: Couldn't write '1' to 'net/ipv4/tcp_syncookies', ignoring: No such file or directory

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
(cherry picked from commit 33410da17f40dd949d29d1daa20c2c89b6741ce5)

### CODE REVIEW

**Comment by nefethael** [comment]
Hi, 

Be careful if you use a CAN bus to check if this [patch](https://patchwork.ozlabs.org/patch/1182162/) is applied, see this [thread](https://github.com/systemd/systemd/issues/9194) for more details.

Kind regards,
Vincent

**Comment by otavio** [comment]
Cool; mind to send it as a PR?

**Comment by nefethael** [comment]
@otavio Which kind of PR do you prefer? a patch file in meta-freescale, a PR in linux-fslc?  which branch?

**Comment by otavio** [comment]
For the kernel fork. 

If possible, the branches you know would be good for community.

We sent the 4.14-2.3 yesterday and there are people still using old ones.

**Comment by nefethael** [comment]
@otavio I'm not using meta-freescale for a while so please tell me ;) I'll send it on monday.

**Comment by otavio** [comment]
- 4.19.x+fslc
- 4.14-2.3.x-imx

Those are the latest ones.

**Comment by schnitzeltony** [comment]
Have not yet found the time to read that thread completely and what the solution is. 

Hope that I can offer a solution within this week

**Pull request merged**
