### PR TITLE
Add recipes to support ISP ( i.MX 8M Plus)

### PR DESCRIPTION
**Pull request by chrisdimich**

### CODE REVIEW

**Comment by kraj** [comment]
These are failing for non-fsl machines e..g. which use linux-yocto for kernel so please make them imx soc familiy specific or fix them see
https://errors.yoctoproject.org/Errors/Details/571336/
https://errors.yoctoproject.org/Errors/Details/571337/

**Comment by otavio** [comment]
@chrisdimich can you look at this?

**Comment by zandrey** [comment]
@chrisdimich I was late also to post a comment regarding this PR.

It looks like it brings `bash` in RDEPENDS, which would fail to build if `GPLv3` license is blacklisted. Scripts should be made shell-neutral, otherwise this package cannot be included in images with _no-GPLv3_ setup.

-- andrey

**Comment by otavio** [comment]
Agreed, this can be another PR fixing the bashism issues. Mind to report it and mention @chrisdimich ?

**Comment by zandrey** [comment]
> 
> 
> Agreed, this can be another PR fixing the bashism issues. Mind to report it and mention @chrisdimich ?

Sure, I've just opened #654 to record this prospective re-work.

-- andrey

**Comment by chrisdimich** [comment]
Sure, let me look at this.

**Pull request merged**
