### PR TITLE
machines: Adjust for using new location of tune files from core

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Please hold on merging this until [1] is merged into OE-core

[1] https://lists.openembedded.org/g/openembedded-core/topic/patch_v2_0_3_tunes_the/84935312?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,84935312

**Comment by kraj** [comment]
Please merge this now since relevant OE-core commit is not in master.

**Comment by otavio** [comment]
To merge or not merge? Your message is confusing.

**Comment by kraj** [comment]
heh typo :) please merge

**Pull request merged**
