### PR TITLE
optee: Upgrade 3.17.0.imx to 3.19.0.imx

### PR DESCRIPTION
**Pull request by MrCry0**
NXP BSP lf-5.15.71_2.2.0 uses op-tee 3.19.0.imx.
Upgrade optee-os, optee-client, and optee-test accordingly.

Add missed support for imx93evk platform.

...

Part of https://github.com/Freescale/meta-freescale/issues/1343

### CODE REVIEW

**Comment by MrCry0** [comment]
@otavio I might be compatible with clang, test it later.

**Comment by otavio** [comment]
@MrCry0 please remove the toolchain override so @kraj can validate it at his side.

**Comment by MrCry0** [comment]
> @MrCry0 please remove the toolchain override so @kraj can validate it at his side.

@otavio sorry, don't get it. Do you want me to revert gcc override commit in this PR?

**Comment by otavio** [comment]
@kraj can you validate the clang build?

**Review by otavio — APPROVED** [review]

**Review by angolini — APPROVED** [review]

**Comment by kraj** [comment]
> @kraj can you validate the clang build?

this still needs fixing to build with clang, I have posted a followup to get it going with clang see https://github.com/Freescale/meta-freescale/pull/1373

**Pull request merged**
