### PR TITLE
u-boot-imx upgrade to version 2021.04

### PR DESCRIPTION
**Pull request by pberginkonsult**
Follow the version released by NXP in meta-imx for their fork u-boot-imx.

These commits are tested on a i.mx8mm_evk board. It boots to u-boot console and it is possible to continue and boot Linux kernel.

```
U-Boot SPL 2021.04-imx_v2021.04_5.10.35_2.0.0 (Jul 05 2021 - 19:33:52 +0000)
DDRINFO: start DRAM init
DDRINFO: DRAM rate 3000MTS
DDRINFO:ddrphy calibration done
DDRINFO: ddrmix config done
SEC0:  RNG instantiated
Normal Boot
Trying to boot from MMC2
NOTICE:  BL31: v2.4(release):lf-5.10.35-2.0.0-rc2-0-gec35fef92
NOTICE:  BL31: Built : 09:05:55, May 28 2021


U-Boot 2021.04-imx_v2021.04_5.10.35_2.0.0 (Jul 05 2021 - 19:33:52 +0000)

alloc space exhausted
CPU:   i.MX8MMQ rev1.0 1800 MHz (running at 1200 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 45C
Reset cause: POR
Model: NXP i.MX8MM EVK board
DRAM:  2 GiB
TCPC:  Vendor ID [0x1fc9], Product ID [0x5110], Addr [I2C1 0x52]
Power supply on USB2
TCPC:  Vendor ID [0x1fc9], Product ID [0x5110], Addr [I2C1 0x50]
MMC:   FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... OK
[*]-Video Link 0adv7535_mipi2hdmi adv7535@3d: Can't find cec device id=0x3c
fail to probe panel device adv7535@3d
mxs_video lcdif@32e00000: failed to get any video link display timings
probe video device failed, ret -22

        [0] lcdif@32e00000, video
        [1] mipi_dsi@32e10000, video_bridge
        [2] adv7535@3d, panel
In:    serial
Out:   serial
Err:   serial
SEC0:  RNG instantiated

 BuildInfo:
  - ATF ec35fef

flash target is MMC:2
Net:   eth0: ethernet@30be0000
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0 
u-boot=> 
```

There is an error `alloc space exhausted` during boot which is caused by CONFIG_SYS_MALLOC_F_LEN set to 0x8000 in commit https://source.codeaurora.org/external/imx/uboot-imx/commit/configs/imx8mm_evk_defconfig?h=lf_v2021.04&id=85e00a89b64369732853971bf3ac8d889bd73993 . It is fixed by increasing the value to 0x10000. Similar solution as in https://github.com/u-boot/u-boot/commit/b6b1b38a94b45c4580b52076c0aa5f72cc3ce0eb. How do we handle this?

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
@thochstein @zandrey please take a look at this.

**Review by zandrey — COMMENTED** [review]
LGTM, I'd test this out on `imx8mp-lpddr4-evk` machine today.

The issue with early malloc area exhaustion is actually present in most of machines, and the commit referenced is addressing it for _i.MX8M Plus_ only.

I can only suggest that upstream patches are picked up here in the layer, and maybe @thochstein can forward them internally to be applied to _u-boot-imx_ tree?

**Comment by pberginkonsult** [comment]
> The issue with early malloc area exhaustion is actually present in most of machines, and the commit referenced is addressing it for _i.MX8M Plus_ only.
> 
> I can only suggest that upstream patches are picked up here in the layer, and maybe @thochstein can forward them internally to be applied to _u-boot-imx_ tree?

For imx8mm_evk_defconfig everything looks okay (CONFIG_SYS_MALLOC_F_LEN=0x10000) upstream in u-boot repo. The issue is caused by a commit only i uboot-imx repo. If we don't have a way to contribute back to uboot-imx and if there are potentially more targets with bad default config I'm not that keen on adding just one patch for one target. But open for suggestions.

**Comment by otavio** [comment]
@thochstein how do you this workflow could work? Should we collect the patches on the layer or start a branch for it?

**Comment by otavio** [comment]
@pberginkonsult I'll merge this as is. If we need to apply changes we can do as patches and then forward the needed patches for @thochstein to apply them internally.

**Pull request merged**
