### PR TITLE
linux-fslc-lts: upgrade 4.19.56 -> 4.19.66

### PR DESCRIPTION
**Pull request by schnitzeltony**
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by angolini** [comment]
I think this is a duplication of #147 

If it's not, please, reopen the PR

**Comment by schnitzeltony** [comment]
This is for master #147 is for warrior

**Comment by schnitzeltony** [comment]
And I don't find a knob to reopen...

**Comment by angolini** [comment]
My bad. Sorry.

**Pull request merged**
