### PR TITLE
Backup a patch to fix build bug of perf.

### PR DESCRIPTION
**Pull request by leimaohui**
Signed-off-by: Lei Maohui <leimaohui@cn.fujitsu.com>

### CODE REVIEW

**Comment by otavio** [comment]
Please, adjust the commit log.

@rehsack please review.

**Comment by otavio** [comment]
Also, this need to be against master.

**Comment by rehsack** [comment]
@otavio, @leimaohui - probably best getting it into master and from there do a backport. I suggest closing this one and open a new one with the backport once https://github.com/Freescale/meta-freescale/pull/376 is integrated.

**Comment by otavio** [comment]
I am closing this as once we merge this I'll sync dunfell branch.

**Pull request closed without merging**
