### PR TITLE
NXP WiFi firmware

### PR DESCRIPTION
**Pull request by thochstein**
Revised fix for #1639. Depends on OE-Core update to `linux-firmware`. That is currently pending a final internal review before I submit the change to OE-Core.

### CODE REVIEW

**Comment by thochstein** [comment]
This is a draft. It does depend on `linux-firmware` being updated in OE-Core. That is currently pending a final internal review before I submit the change to OE-Core.

A second issue is I seem unable to resolve a `Multiple providers` warning:
```
NOTE: Multiple providers are available for runtime linux-firmware-nxp9098-common (firmware-nxp-wifi, linux-firmware)
Consider defining a PREFERRED_RPROVIDER entry to match linux-firmware-nxp9098-common
NOTE: Multiple providers are available for runtime linux-firmware-nxp8997-common (firmware-nxp-wifi, linux-firmware)
Consider defining a PREFERRED_RPROVIDER entry to match linux-firmware-nxp8997-common
```

I added preferred runtime providers in `imx-base.inc` but it doesn't help.
```
 MACHINE_FIRMWARE:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp8997-pcie', 'firmware-nxp-wifi-nxp8997-pcie', '', d)}"
 MACHINE_EXTRA_RRECOMMENDS:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp8997-pcie', 'kernel-module-nxp-wlan', '', d)}"
+PREFERRED_RPROVIDER_linux-firmware-nxp8997-common = "firmware-nxp-wifi-nxp8997-common"
+PREFERRED_RPROVIDER_linux-firmware-nxp8997-pcie = "firmware-nxp-wifi-nxp8997-pcie"

 MACHINE_FIRMWARE:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp8997-sdio', 'firmware-nxp-wifi-nxp8997-sdio', '', d)}"
 MACHINE_EXTRA_RRECOMMENDS:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp8997-sdio', 'kernel-module-nxp-wlan', '', d)}"
+PREFERRED_RPROVIDER_linux-firmware-nxp8997-sdio = "firmware-nxp-wifi-nxp8997-sdio"

 MACHINE_FIRMWARE:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp9098-pcie', 'firmware-nxp-wifi-nxp9098-pcie', '', d)}"
 MACHINE_EXTRA_RRECOMMENDS:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp9098-pcie', 'kernel-module-nxp-wlan', '', d)}"
+PREFERRED_RPROVIDER_linux-firmware-nxp9098-common = "firmware-nxp-wifi-nxp9098-common"
+PREFERRED_RPROVIDER_linux-firmware-nxp9098-pcie = "firmware-nxp-wifi-nxp9098-pcie"

 MACHINE_FIRMWARE:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp9098-sdio', 'firmware-nxp-wifi-nxp9098-sdio', '', d)}"
 MACHINE_EXTRA_RRECOMMENDS:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'nxp9098-sdio', 'kernel-module-nxp-wlan', '', d)}"
+PREFERRED_RPROVIDER_linux-firmware-nxp9098-sdio = "firmware-nxp-wifi-nxp9098-sdio"
```

**Comment by sapiippo** [comment]
Haven't used PREFERRED_RPROVIDER, but shouldn't it be set to ${PN} and not the individual subpackages?

Alternatively, could the firmware-nxp-wifi-* packages just have dependency to the linux-firmware-nxp* packages instead of adding conflicting packages?

**Comment by thochstein** [comment]
> Haven't used PREFERRED_RPROVIDER, but shouldn't it be set to ${PN} and not the individual subpackages?

Yes, of course, thank you! The error was hinting at that.

> Alternatively, could the firmware-nxp-wifi-* packages just have dependency to the linux-firmware-nxp* packages instead of adding conflicting packages?

From reading the Yocto manual it sounds like `RREPLACES` and `RCONFLICTS` are for a different use case and are needed at least technically.

https://docs.yoctoproject.org/singleindex.html#term-RREPLACES

**Comment by junzhuimx** [comment]
@thochstein  I think your change is OK, as firmware-nxp-wifi contains the latest NXP Wi-Fi firmware for Community/customers to earlier access. 
NXP publish the latest NXP Wi-Fi firmware in imx-firmware.git firstly, and then upstream them to linux-firmware.git later.

**Review by otavio — APPROVED** [review]

**Pull request merged**
