### PR TITLE
linux-imx: Remove duplicate CRYPTO_SHA512 from defconfig

### PR DESCRIPTION
**Pull request by kevswims**
The mx8 defconfig already contains CRYPTO_SHA512 as a module which is
what is honored so this removes the extra line that also sets
CRYPTO_SHA512 to be built in

### CODE REVIEW

**Comment by otavio** [comment]
@kevswims please check our `linux-fslc-imx` recipe as it offer stable fixes and check if we need to do same fix.

@thochstein @zandrey

**Comment by kevswims** [comment]
@otavio Good catch. That one had it duplicated as well. 

Grep of all the defconfigs for that option looks correct now:
```linux/linux-fslc-imx/imx/defconfig:CONFIG_CRYPTO_SHA512=m
linux/linux-fslc-imx/mx8/defconfig:CONFIG_CRYPTO_SHA512_ARM64_CE=m
linux/linux-fslc-imx/mx8/defconfig:CONFIG_CRYPTO_SHA512=m
linux/linux-imx/imx/defconfig:CONFIG_CRYPTO_SHA512=m
linux/linux-imx/mx8/defconfig:CONFIG_CRYPTO_SHA512_ARM64_CE=m
linux/linux-imx/mx8/defconfig:CONFIG_CRYPTO_SHA512=m
```

**Comment by zandrey** [comment]
@kevswims Spot on!

This is reported now from `kernel_configcheck()` in `mismath-all.txt`:

```
Config: CONFIG_SND_SOC_SOF_IMX8
From: /development/yocto-master/build-output/work-shared/imx8mmevk/kernel-source/.kernel-meta/configs/defconfig
Requested value:  CONFIG_SND_SOC_SOF_IMX8=m
Actual value:

Config: CONFIG_CRYPTO_SHA512
From: /development/yocto-master/build-output/work-shared/imx8mmevk/kernel-source/.kernel-meta/configs/defconfig /development/yocto-master/build-output/work-shared/imx8mmevk/kernel-source/.kernel-meta/configs/defconfig
Requested value:  CONFIG_CRYPTO_SHA512=y
CONFIG_CRYPTO_SHA512=m
Actual value:     CONFIG_CRYPTO_SHA512=m

Config: CONFIG_CRYPTO_SHA512
From: /development/yocto-master/build-output/work-shared/imx8mmevk/kernel-source/.kernel-meta/configs/defconfig /development/yocto-master/build-output/work-shared/imx8mmevk/kernel-source/.kernel-meta/configs/defconfig
Requested value:  CONFIG_CRYPTO_SHA512=y
CONFIG_CRYPTO_SHA512=m
Actual value:     CONFIG_CRYPTO_SHA512=m
```

Please format your commit proper according to [OE Commit Format Standard](https://www.openembedded.org/wiki/How_to_submit_a_patch_to_OpenEmbedded#Committing_your_patch)

@thochstein Can you take a look at why `CONFIG_SND_SOC_SOF_IMX8` is reported not to be present in the final config? Are there any dependencies missing?

**Comment by zandrey** [comment]
> 
> @thochstein Can you take a look at why `CONFIG_SND_SOC_SOF_IMX8` is reported not to be present in the final config? Are there any dependencies missing?

Got it a bit further, the `CONFIG_SND_SOC_SOF_IMX8_SUPPORT` is missing in the `defconfig`.

After selecting it - the error about `CONFIG_SND_SOC_SOF_IMX8` is gone from `mismath-all.txt`; fragment extracted after `CONFIG_SND_SOC_SOF_IMX8_SUPPORT` selection looks like this:
```
CONFIG_SND_SOC_SOF_IMX8_SUPPORT=y
CONFIG_SND_SOC_SOF_IMX8=m
```

@thochstein Do you know why this config option missing? Is it not supported or just accidentally missed out?

**Comment by zandrey** [comment]
@otavio @kevswims I'd be doing the kernel recipe updates today, and can include this `CONFIG_CRYPTO_SHA512` original commit into the PR, provided that @kevswims would have it properly formatted.

For the `CONFIG_SND_SOC_SOF_IMX8` I'd have to wait for @thochstein to comment on the missing dependency.

-- andrey

**Comment by thochstein** [comment]
> The mx8 defconfig already contains CRYPTO_SHA512 as a module

I've reported this back to our kernel team and they are investigating.

> For the CONFIG_SND_SOC_SOF_IMX8 I'd have to wait for @thochstein to comment on the missing dependency.

@zandrey Seems the name was incorrect and updated in these sequential commits:
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.3_2.0.0&id=bd2eec7f4bfc14a230524ef7c1b453ff65b670ef
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.3_2.0.0&id=90c77380fe135fdbd9fa702b487d5de397cc15b6
Please note the name and the value are changed.

**Comment by kevswims** [comment]
@zandrey I have added the signed-off line to the patch.

**Comment by zandrey** [comment]
> 
> 
> @zandrey I have added the signed-off line to the patch.

Great, thanks a lot! I hope you wouldn't mind if I take your commit from here and stack it up in my upcoming PR?

-- andrey

**Comment by zandrey** [comment]
> @zandrey Seems the name was incorrect and updated in these sequential commits:
> https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.3_2.0.0&id=bd2eec7f4bfc14a230524ef7c1b453ff65b670ef
> https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.3_2.0.0&id=90c77380fe135fdbd9fa702b487d5de397cc15b6
> Please note the name and the value are changed.

I see now, it was probably a WIP in 5.4-1.0.0, as the only place the `CONFIG_SND_SOC_SOF_IMX8_SUPPORT` is used is actually in [sound/soc/sof/imx/Kconfig](https://github.com/Freescale/linux-fslc/blob/e0743cf91d9e44a810e6f86d22db2bfc89e5016d/sound/soc/sof/imx/Kconfig#L14) to create a dependency for `CONFIG_SND_SOC_SOF_IMX8`.

I would define the `CONFIG_SND_SOC_SOF_IMX8_SUPPORT=y` for `5.4-1.0.0-imx` branch now, and once the *5.4-2.0.0* is out - this would be taken care of in the *defconfig* from you.

Would that be OK?

**Comment by kevswims** [comment]
@zandrey It's not a problem if you pull this commit into your PR. Thanks!

**Comment by thochstein** [comment]
> I would define the CONFIG_SND_SOC_SOF_IMX8_SUPPORT=y for 5.4-1.0.0-imx branch now, and once the 5.4-2.0.0 is out - this would be taken care of in the defconfig from you.
> 
> Would that be OK?

Works for me.

**Comment by zandrey** [comment]
@kevswims @thochstein I've opened #391 which contains the patch from this one. This one can be closed now.

Thanks a lot!

-- andrey

**Pull request closed without merging**
