### PR TITLE
linux-fslc-imx: fix defconfig path

### PR DESCRIPTION
**Pull request by maximdeclercq**
`linux_fslc.inc` specifies `file://defconfig` in `SRC_URI`.

### CODE REVIEW

**Comment by maximdeclercq** [comment]
Is it possible that I'm missing something for Yocto to search the IMX subdirectory? I am trying to use the FSLC framebuffer distro with the `linux-fslc-imx` kernel. 

This is the error:
```
ERROR: linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a-r0 do_fetch: Fetcher failure: Unable to find file file://defconfig anywhere. The paths that were searched were:
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/fslc
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/fslc
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/fslc
    /work/sources/meta-freescale/recipes-kernel/linux/files/fslc
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/tt-imx7d-pico
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/tt-imx7d-pico
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/tt-imx7d-pico
    /work/sources/meta-freescale/recipes-kernel/linux/files/tt-imx7d-pico
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/use-mainline-bsp
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/use-mainline-bsp
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/use-mainline-bsp
    /work/sources/meta-freescale/recipes-kernel/linux/files/use-mainline-bsp
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/armv7ve
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/armv7ve
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/armv7ve
    /work/sources/meta-freescale/recipes-kernel/linux/files/armv7ve
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/arm
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/arm
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/arm
    /work/sources/meta-freescale/recipes-kernel/linux/files/arm
    /work/sources/meta-teletask/recipes-kernel/linux/linux-fslc-imx/
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx-5.4.106+gitAUTOINC+eb6f11341a/
    /work/sources/meta-freescale/recipes-kernel/linux/linux-fslc-imx/
    /work/sources/meta-freescale/recipes-kernel/linux/files/
    /work/yocto-build/downloads
```

**Comment by otavio** [comment]
What is the value of `IMX_DEFAULT_BSP`?

**Comment by maximdeclercq** [comment]
`IMX_DEFAULT_BSP` is `mainline-bsp`, should it be `nxp`?

**Comment by otavio** [comment]
If you wish to use this Linux kernel, yes. Or you can use the mainline BSP.

**Comment by maximdeclercq** [comment]
Oh alright, thanks. Then [this](https://github.com/Freescale/meta-freescale-3rdparty/pull/122) should probably be fixed to use the NXP BSP on the IMX7D.

**Pull request closed without merging**
