### PR TITLE
Add OP-TEE support for imx6qdlsabre* machines

### PR DESCRIPTION
**Pull request by thochstein**

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Review by twoerner — COMMENTED** [review]
this commit breaks the following builds for me:
- imx233-olinuxino-maxi
- imx53qsb
- imx28evk

```
| ERROR: _exec_cmd: install -m 0644 -D /z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/make_dtb_boot_files /z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/work/imx233_olinuxino_maxi-oe-linux-gnueabi/core-image-base/1.0-r0/tmp-wic/boot.2/make_dtb_boot_files returned '1' instead of 0
| output: install: cannot stat '/z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/make_dtb_boot_files': No such file or directory

ERROR: Task (/opt/oe/configs/z/build-master/imx233-olinuxino-maxi/layers/openembedded-core/meta/recipes-core/images/core-image-base.bb:do_image_wic) failed with exit code '1'
```

**Comment by twoerner** [comment]
specifically the `imx-base.inc: Fix optee boot images` commit

**Comment by otavio** [comment]
@twoerner does reverting this one fixes the issue? @thochstein can you take a look?

**Comment by twoerner** [comment]
@otavio yes.

if i checkout the master HEAD then "`git revert 0407a9ecbaedd8aae6be96225632dbe534840e44`" the builds complete successfully again.

**Comment by thochstein** [comment]
Will do. Something strange going on...

**Comment by thochstein** [comment]
@twoerner, can you try the fix? https://github.com/Freescale/meta-freescale/pull/850

**Pull request merged**
