### PR TITLE
[master] linux-fslc: 6.6.50 -> 6.11.0

### PR DESCRIPTION
**Pull request by Livius90**
- Update linux-fslc: 6.6.50 -> 6.11.0

### CODE REVIEW

**Comment by otavio** [comment]
Thank you for looking at this. Please keep the 6.6 kernel but rename it to LTS, as we did for the 6.1.

The 6.11 kernel should be a new recipe without the LTS suffix, so the flavor they choose is transparent to the user.

While you are on it, if you can update the 6.1 and 6.6 recipes to the latest version, that would be great. We can do the same when doing the backports. I have updated the respective branches in our repository.

**Comment by Livius90** [comment]
@otavio 
Do you like to keep `linux-fslc-lts_6.1.bb` also?

**Comment by otavio** [comment]
I think that for now it's important to keep as it is maintained and there might be users of it. Maybe when the next LTS is released, then we can drop it. What do you think?

**Comment by Livius90** [comment]
In master branch `linux-fslc-lts_6.1.bb` is useless for future, because now the latest official LTS is v6.6.x which available as an LTS, `linux-fslc-lts_6.6.bb`. To keep `linux-fslc-lts_6.1.bb` can be important only in `scarthgap`, because it is possible that somebody still use it in a released `scarthgap` layer.

https://www.kernel.org/

**Comment by otavio** [comment]
You have a valid point. So, move to 6.1 to 6.6 LTS in the master branch, and keep the 6.1 version when preparing the backport.

**Comment by Livius90** [comment]
> You have a valid point. So, move to 6.1 to 6.6 LTS in the master branch, and keep the 6.1 version when preparing the backport.

Done

**Comment by otavio** [comment]
Please prepare the pull request for backporting and then we can remove this 6.1 here in master branch.

**Comment by Livius90** [comment]
I think you can use the Backport CI action and it will generate this PR automatically.

**Pull request merged**
