### PR TITLE
L5.4.3-1.0.0 Kernel upgrade

### PR DESCRIPTION
**Pull request by panfir**

### CODE REVIEW

**Comment by otavio** [comment]
@panfir I am queueing those patches here at master-next branch. Please rebase it.

**Comment by otavio** [comment]
You need to rebase it on top of master as some of your commits where already done there.

**Comment by panfir** [comment]
> You need to rebase it on top of master as some of your commits where already done there.

yeah, duplicated work

**Comment by panfir** [comment]
> > You need to rebase it on top of master as some of your commits where already done there.
> 
> yeah, duplicated work

I've tested for:
#MACHINE ??= 'imx6qdlsabresd'                                                   
#MACHINE ??= 'imx6sllevk'                                                       
#MACHINE ??= 'imx7ulpevk'                                                       
#MACHINE ??= 'imx7dsabresd'                                                     
#MACHINE ??= 'imx8mmevk'                                                        
#MACHINE ??= 'imx8mnevk'                                                        
#MACHINE ??= 'imx8mqevk'                                                        
#MACHINE ??= 'imx8qxpmek'                                                        
#MACHINE ??= 'imx8qmmek'

**Pull request closed without merging**
