### PR TITLE
Dunfell enhancements

### PR DESCRIPTION
**Pull request by varigigi**
general enhancements for iMX6, iMX7 and iMX8 machines

### CODE REVIEW

**Comment by otavio** [comment]
Please prepare the PR on top of master, and then we can cherry-pick the fixes if need, for dunfell. We need to avoid applying fixes on dunfell directly or be forgotten and missed on master.

**Comment by varigigi** [comment]
Thanks Otavio,
master PR sent.

**Comment by otavio** [comment]
I'll close this PR as we should do the backport from master (using `git cherry-pick -x`) from master once it is merged.

**Comment by varigigi** [comment]
Will the cherry-pick process be automatic or any  action is required on my side?

**Pull request closed without merging**
