### PR TITLE
imx-seco-libs: Fix build with clang

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by MrCry0** [comment]
@kraj Oh, my, I lost a similar fix for clang in my PR. But your one is better.
@otavio I could include these commits in the PR https://github.com/Freescale/meta-freescale/pull/1363
Would you mind?

**Comment by kraj** [comment]
> @kraj Oh, my, I lost a similar fix for clang in my PR. But your one is better. @otavio I could include these commits in the PR #1363 Would you mind? Building is retested.

its fine as long as it gets applied.

**Comment by MrCry0** [comment]
> its fine as long as it gets applied.

@kraj thanks, I rebased that PR.

**Comment by otavio** [comment]
Closing this in favor of #1363.

**Pull request closed without merging**
